spring:
  application:
    name: zuul
  rabbitmq:
    host: 192.168.115.132
    port: 5672
    username: admin
    password: admin
    
server:
  port: 3001

zuul:
  retryable: true
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream